dataset_name: "edr3"
base_table_filename: "edr3-rv-good-plx-result.fits.gz"
noise_config_file: "config/noise.yaml"

remote_basedir: "remote"
results_basedir: "results"

sims_config_file: "config/sims.yaml"

gaia:
  credentials_file: ""
  # credentials_file: "/path/to/gaia/archive.login"
  # or...
  # user = "username"
  # password = "password"

# Noise model postprocessing parameters
noise:
  color_smoothing_scale: 0.25
  mag_smoothing_scale: 0.5
