# A random number seed
seed: 11239

# Minimum number of RVS transits required to estimate the noise model
min_nb_transits: 3

# The color and magnitude grid specification
min_color: 0.0
max_color: 5.5
num_color: 45

min_mag: 4.5
max_mag: 16.0
num_mag: 30

# The number of targets to fit at once
targets_per_fit: 1000

# The number of SVI optimization steps to run
num_optim: 20000

# The number of random subsets to execute per inference
num_iter: 50
