# A random number seed
seed: 11239

# Minimum number of RVS transits required to estimate the noise model
min_nb_transits: 3

# The color and magnitude grid specification
num_color: 20
num_mag: 30

# The number of SVI optimization steps to run
num_optim: 1000
