channels:
  - conda-forge
dependencies:
  - python =3.9
  - git =2.30.2
  - curl =7.77.0
  - tar =1.34
  - open-fonts =0.7.0
  - numpy =1.21.0
  - scipy =1.7.0
  - matplotlib =3.4.2
  - jupyter =1.0.0
  - jupyterlab =3.0.16
  - jupytext =1.11.3
  - astropy =4.2.1
  - astroquery =0.4.3
  - fitsio =1.1.4
  - pandas =1.3.0
  - pyyaml =5.4.1
  - numpyro =0.7.1
  - pip = 21.1.3
  - pip:
      - kepler.py==0.0.6
      - tensorflow_probability==0.13.0
